"""empty message

Revision ID: de0fdd42a99f
Revises: 42a5bef46c32
Create Date: 2019-11-24 13:42:56.962572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de0fdd42a99f'
down_revision = '42a5bef46c32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorited_movies')
    op.drop_table('later_movies')
    op.drop_table('movies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('movies_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('movie_api_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='movies_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('later_movies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name='later_movies_movie_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='later_movies_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='later_movies_pkey')
    )
    op.create_table('favorited_movies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name='favorited_movies_movie_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='favorited_movies_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorited_movies_pkey')
    )
    # ### end Alembic commands ###
